language: go

services:
  - docker

go:
  - 1.9

env:
  - CGO_ENABLED=0

script:
  - go test
  - go build -ldflags "-s -w -X main.build=$TRAVIS_BUILD_NUMBER -X main.rev=$TRAVIS_COMMIT" -a -tags netgo
  - cp /etc/ssl/certs/ca-certificates.crt .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "nytimes/drone-openapi:latest" .;
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "nytimes/drone-openapi:latest";
    fi

